version: '3.8'

services:
  resume-generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resume-generator
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./templates:/app/templates
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1 