apiVersion: v1
kind: Service
metadata:
  name: resume-generator-service
  namespace: resume-app
spec:
  type: LoadBalancer
  selector:
    app: resume-generator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000 